Add game instance class
mac2648/Redemption pull request #32
Opened 2024-02-13 21:30 UTC by thakkarnandish

2024-02-14 21:48 UTC, Entwistle-905 reviewed
it has a merge conflict but the codes are good :)

2024-02-14 21:57 UTC, mac2648 requested changes

2024-02-14 21:57 UTC, mac2648 commented on Source/Redemption/Public/RedemptionPlayer.h
> +#include "Engine/GameInstance.h"
please include this in the cpp file there is no reason for it to be in the h file

2024-02-15 14:02 UTC, Entwistle-905 approved these changes

2024-02-15 14:39 UTC, closed without merging