Added functionality to heal player when consumes dead body
mac2648/Redemption pull request #47
Opened 2024-02-15 17:11 UTC by thakkarnandish

2024-02-15 23:44 UTC, mac2648 requested changes
there is a small thing, if you look at the health component cpp you will see this
![Screenshot 2024-02-15 184323](https://github.com/mac2648/Redemption/assets/60781347/53df7d0f-393d-49ab-bddd-277a153343cb)
we need that in the set health function too, because other wise the player will heal but will continue to have the HUD saying it is not full health

2024-02-16 00:28 UTC, Entwistle-905 approved these changes

2024-02-16 00:28 UTC, mac2648 approved these changes

2024-02-16 03:32 UTC, merged

2024-02-28 17:49 UTC, DoopweeSLC commented on Source/Redemption/Private/InteractWidgetComponent.cpp
> +		}
I'd much rather see this as if player wrapping the rest of the code.