New main menu
mac2648/Redemption pull request #58
Opened 2024-02-22 16:20 UTC by deepakpaul77

created Main menu with functionality for start and quit button

2024-02-22 18:10 UTC, Entwistle-905 requested changes

2024-02-22 18:10 UTC, Entwistle-905 commented on Source/Redemption/Public/MainMenuWidget.h
> +	virtual void NativeConstruct() override;
on our code standard we need to put public functions before protected functions

2024-02-22 18:10 UTC, Entwistle-905 commented on Source/Redemption/Private/MainMenuWidget.cpp
> +
there are a lot of empty lines please delete them.

2024-02-23 07:27 UTC, thakkarnandish commented
![image](https://github.com/mac2648/Redemption/assets/114674831/51f37aeb-0e93-4f17-b6e9-8d77d43ab648)
 I got an error when I tried to run the menu level, I might be doing it wrong??

2024-02-28 20:58 UTC, mac2648 commented
I tried it on my end and it worked fine

2024-02-28 21:09 UTC, Entwistle-905 commented on Content/UI/MenuGameMode.uasset
Recourses😂

2024-02-28 21:10 UTC, mac2648 commented on Content/UI/MenuGameMode.uasset
someone created the folder with a typo, for the first time it was not me

2024-03-06 00:28 UTC, mac2648 approved these changes

2024-03-06 20:22 UTC, Entwistle-905 approved these changes

2024-03-07 14:32 UTC, merged